--TẠO DATABASE VÀ XÓA
CREATE DATABASE ONTAPCSDL
CREATE DATABASE ONTAP
--DROP DATABASE <tên database cần xóa>

--TẠO BẢNG TRONG SQL
CREATE TABLE HOCSINH
(
MASV INT PRIMARY KEY,
TENSV NVARCHAR(50)
)
INSERT INTO DBO.HOCSINH
values (1, N'Nguyễn Khánh Vân')
insert into dbo.HOCSINH
values (2, N'Trần Võ Thanh Ngân')
insert into dbo.HOCSINH
values(3, N'Trần Quốc Tuấn')

CREATE TABLE GIANGVIEN
(MAGV INT PRIMARY KEY,
TENGV NVARCHAR(50),
MABM NVARCHAR(8)
)
ALTER TABLE GIANGVIEN ADD MABM INT;
INSERT INTO DBO.GIANGVIEN
VALUES (1, N'Trần Mạnh Tuấn')
INSERT INTO DBO.GIANGVIEN
VALUES (2, N'Bùi Xuân Huy')
INSERT INTO DBO.GIANGVIEN
VALUES (3, N'Trương Việt Phương')
INSERT INTO DBO.GIANGVIEN
VALUES (4,N'Bùi Hoàng Thành')

CREATE TABLE BOMON
(MABM INT PRIMARY KEY,
TENBM NVARCHAR(8)
)
INSERT INTO BOMON
VALUES (1,'TOÁN')
INSERT INTO BOMON
VALUES (2,'LÝ')
INSERT INTO BOMON
VALUES (3,'HÓA')
INSERT INTO BOMON
VALUES (4,'ANH')

ALTER TABLE dbo.BOMON ADD CONSTRAINT FK_MABM FOREIGN KEY(MABM) REFERENCES dbo.GIANGVIEN(MABM)

