--INNER JOIN -> kiểu cũ -> có thể sau này sẽ không được hỗ trợ
--Mọi JOIN đều cần điều kiện
SELECT *
FROM GIAOVIEN, BOMON
WHERE BOMON.MABM=GIAOVIEN.MABM

--INNER JOIN KIỂU MỚI (NÊN DÙNG)
SELECT *
FROM GIAOVIEN 
INNER JOIN BOMON ON BOMON.MABM=GIAOVIEN.MABM 
AND BOMON.TRUONGBM=''

--JOIN BẮT BUỘC PHẢI CÓ ĐK THÊM VÀO
SELECT *
FROM KHOA
JOIN BOMON ON BOMON.MAKHOA=KHOA.MAKHOA

--FULL OUTER JOIN
SELECT *
FROM GIAOVIEN, BOMON
WHERE BOMON.MABM=GIAOVIEN.MABM

--Gom 2 bảng lại theo đk bên nào không có dữ liệu thì để null
SELECT *
FROM GIAOVIEN 
FULL OUTER JOIN BOMON ON BOMON.MABM=GIAOVIEN.MABM

--CROSSN JOIN LÀ TỔ HỢP MỖI RECORD CỦA BẢNG A VỚI ALL RECORD BẢNG A
SELECT *
FROM GIAOVIEN CROSS JOIN BOMON
