--SELECT INTO
--Lấy hết dữ liệu của bảng GV đưa vào bảng TableA 
--Bảng này có các record t/ư như bảng GV
SELECT * INTO TableA 
FROM GIAOVIEN
--TẠO RA 1 BẢNG TABLEB MỚI CÓ 1 CỘT DỮ LIỆU LÀ HOTEN TƯƠNG ỨNG NHƯ BẢNG GV
--DỮ LIỆU LẤY TỪ BẢNG GV
SELECT HOTEN INTO TableB
FROM GIAOVIEN

--TẠO RA 1 BẢNG TABLEB MỚI CÓ 1 CỘT DỮ LIỆU LÀ HOTEN TƯƠNG ỨNG NHƯ BẢNG GV
--VỚI ĐK LƯƠNG >2000
--DỮ LIỆU LẤY TỪ BẢNG GV


--TẠO BẢNG MỚI TỪ NHIỀU BẢNG
SELECT MAGV,HOTEN,TENBM INTO GVBackup
FROM GIAOVIEN,BOMON
WHERE BOMON.MABM=GIAOVIEN.MABM
DROP TABLE GVBackup

--TẠO RA BẢNG GVBK Y CHANG NHƯNG KHÔNG CÓ DL
SELECT * INTO GVBK
FROM GIAOVIEN
WHERE 6>9
 
SELECT * INTO CloneGV
FROM GIAOVIEN
WHERE 1=0

INSERT INTO CloneGV
SELECT * FROM GIAOVIEN

SELECT *FROM CloneGV
